### PR TITLE
Notification manager class #76

### PR DESCRIPTION
**Pull request by RyanPybus**
Notification Manager class
Methods to:
- add notification associated with user
- delete notification by notification id
- modify notification by id
- retrieve list of all notifications associated with a user

### CODE REVIEW

**Review by anthonyargatoff — APPROVED** [review]
The additions look great

**Review by anthonyargatoff — APPROVED** [review]
There is some commented test code at the bottom of NotificationManager.py

**Comment by RyanPybus** [comment]
Good catch, removed it.

**Review by DyPickard — APPROVED** [review]
this looks good

**Pull request merged**
