### PR TITLE
setup the test automation

### PR DESCRIPTION
**Pull request by Varun2711**
The testing automation with github workflows has been setup. Currently like we talked about in discord about the datetime module's issues with the moments of time prior to Jan 1st 1970 on some OS is causing an issue with the unittest workflow causing it to fail.  But please review and pull the issue to make sure the automation is working correctly in the main repository. If everything goes well then whenever you push, the workflow for flask application testing should work just fine and the workflow for the component_tests with unittest should give an error mentioned above.

### CODE REVIEW

**Comment by Varun2711** [comment]
https://pytest-with-eric.com/integrations/pytest-github-actions/

this is the link to the tutorial that I used to setup github automation

**Review by RyanPybus — APPROVED** [review]
Thanks Varun 
Edit: got it to run on mine, works fine, except for the populate db

**Review by anthonyargatoff — APPROVED** [review]
Changes look good. When merging the _mapScript.js_ file, use the current changes instead of the incoming changes.

**Review by Aayushchaudhary84 — APPROVED** [review]
Looks good

**Pull request merged**
