### PR TITLE
documentation to run flask app #86

### PR DESCRIPTION
**Pull request by Aayushchaudhary84**

### CODE REVIEW

**Review by anthonyargatoff — CHANGES_REQUESTED** [review]
This guide needs to be more specific to our application. For instance, this guide mentions an app.py file, yet we do not have one. What steps should one of our team members follow to start this application?

**Review by Varun2711 — CHANGES_REQUESTED** [review]
to run the application the command is the following:
flask --app flaskr run --debug
the aforementioned command starts a development server.

remove point 2

new point 2:
setup virtual environment: 
initially when you don't have a virtual environment
run this command to create one: python -m venv .venv
after/if you have a virtual environment run the following command to activate the virtual environment: on windows: .venv\Scripts\activate, on max/linux: source .venv/bin/activate

**Review by Varun2711 — APPROVED** [review]
Okay looks good

**Review by anthonyargatoff — APPROVED** [review]
Changes look good

**Pull request merged**
