### PR TITLE
 Calculate distance between 2 coordinates issue #88 

### PR DESCRIPTION
**Pull request by anthonyargatoff**
Created the class, tests, and documentaion for the coordinateCalculator. Its purpose is to return the surface distance between 2 coordinates.

This is attempt 2 at this pull request. First one was wrongly to be merged to main.

### CODE REVIEW

**Review by RyanPybus — APPROVED** [review]
Looks good Anthony, Does the depth attribute from the api matter for this?

**Comment by anthonyargatoff** [comment]
This formula doesn't account for the depth, as we will be measuring spherical distance from 2 coordinates

**Review by Varun2711 — APPROVED** [review]
looks great!

**Review by Aayushchaudhary84 — APPROVED** [review]
Looks good anthony

**Pull request merged**
