### PR TITLE
use case diagram 11

### PR DESCRIPTION
**Pull request by Aayushchaudhary84**
Please review the use case diagram 11 and let me know if any modifications are needed.

### CODE REVIEW

**Review by anthonyargatoff — CHANGES_REQUESTED** [review]
You have repeated steps in your diagram. Use the `<<exception>>` notation instead of repeating steps (see lecture W4_Analysis.pdf slide 37)

**Review by RyanPybus — APPROVED** [review]
Looks good

**Review by Varun2711 — APPROVED** [review]
lacking activation bars, but looks good otherwise.

**Review by Varun2711 — CHANGES_REQUESTED** [review]
need to activation bars to the diagram. looks good otherwise.

**Review by Varun2711 — APPROVED** [review]

**Pull request merged**
