### PR TITLE
flask stuff for issue #45

### PR DESCRIPTION
**Pull request by Varun2711**
very basic flask app. still learning the framework and working out how to produce better quality backend. But let me know how this looks and where I should go from here. Thanks!

### CODE REVIEW

**Review by anthonyargatoff — CHANGES_REQUESTED** [review]
Varun, don't include the .venv folder on github, as it doesn't work across different computers . Instead, create a requirements.txt file (https://www.geeksforgeeks.org/how-to-create-requirements-txt-file-in-python/) and include it in the repo. `pip freeze > requirements.txt`
That way, when each of us is working on flask, we would install our own individual venv and then install the requirements.txt file with `pip install requirements.txt`
Remove the .venv from git, supply a requirements.txt file, and also create a readme guide to help our team to install the venv.

**Comment by Varun2711** [comment]
Hey @anthonyargatoff ! Thanks for the heads up about the virtual environment. It completely left my mind when I was making this pr. It should be fixed now, could you please checkout the changes? I removed the venv directory and added a .gitignore file and a requirements.txt file. Thank you!

**Review by RyanPybus — APPROVED** [review]
Looks good to me

**Review by anthonyargatoff — APPROVED** [review]
Looks good

**Review by anthonyargatoff — CHANGES_REQUESTED** [review]
Can you include a readme or a guide on how to set on? I've cloned your repo, but I have no idea how to start the flask app.

**Comment by anthonyargatoff** [comment]
Why are you using a fork instead of a branch?

**Comment by Varun2711** [comment]
personally just felt a bit safer using a fork rather than a branch, since it's an independent copy. Wanted to make sure I don't accidentally delete everyone's work (I've been learning git command line recently). I will update the readme to include execution instructions as well.

**Comment by Varun2711** [comment]
I will switch to working with a branch after this pr.

**Review by anthonyargatoff — APPROVED** [review]
Changes look good.

**Pull request merged**
